export const FB_LOGIN_START = 'FB_LOGIN_START';
export const FB_LOGIN_ERROR = 'FB_LOGIN_ERROR';
export const FB_LOGIN_CANCELLED = 'FB_LOGIN_CANCELLED';
export const RECEIVE_FB_PROFILE = 'RECEIVE_FB_PROFILE';
export const FB_PROFILE_ERROR = 'FB_PROFILE_ERROR';
export const GET_USER_START = 'GET_USER_START';
export const GET_USER_RECEIVED = 'GET_USER_RECEIVED';
export const GET_USER_NOT_FOUND = 'GET_USER_NOT_FOUND';
export const GET_USER_ERROR = 'GET_USER_ERROR';
export const CREATE_USER_START = 'CREATE_USER_START';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';
export const CREATE_USER_COMPLETE = 'CREATE_USER_COMPLETE';
export const GET_DESTINATION_DATA_START = 'GET_DESTINATION_DATA_START';
export const GET_DESTINATION_DATA_RECEIVED = 'GET_DESTINATION_DATA_RECEIVED';
export const GET_DESTINATION_DATA_ERROR = 'GET_DESTINATION_DATA_ERROR';



export const ADD_GROUP = 'ADD_GROUP';
export const ADD_FRIEND = 'ADD_FRIEND';
export const CREATE_GROUP = 'CREATE_GROUP';
export const LOGIN = 'LOGIN';
export const SET_DESTINATION = 'SET_DESTINATION';
export const SEND_NUDGE = 'SEND_NUDGE';
export const HIDE_USER = 'HIDE_USER';
export const LEAVE_GROUP = 'LEAVE_GROUP';
export const CHANGE_FILTERS = 'CHANGE_FILTER';